### ISSUE TITLE
Populate status with issues assigned to me

### ISSUE THREAD

**Issue by chazy** [jbech-linaro/jipdate#1]
I always imagined the workflow would be

EDITOR=vim linaro-weekly-update
<opens in editor>
[VIRT-1] # Description of issue VIRT-1
# Please fill in updates
[VIRT-5] # This is the most important JIRA issue ever
# Please fill in updates
[VIRT-100] # Fix all the arm64 server problems
# Please fill in updates

Do you know how hard it is to get a list of those issues and pre-populate it?

I'm curious if you think this would not be that hard, then I could add that (and the #comment stuff as well)

thanks.

**Comment by jbech-linaro** [comment]
Consider it done ...  or at least I think it's almost what you are asking for. Just 5 minutes ago I pushed a few more patches that makes it possible to query the Jira server which will reply back a list of open items. This list will be "pre-populated" in the status_update.txt file.

So the workflow now becomes.
1. ./jipdate -c
2. vim status_update.txt
3. ./jipdate

You can also try use the "-x" parameter together with "-c" if you want to exclude stories.

**Comment by chazy** [comment]
So I feel like we wouldn't want to mess with a file being stored, but just show the user a transient editor window, similar to 'git commit' or 'git rebase -i', but maybe the user does want that.

I prefer just running the tool, fill in the blanks, and forget everything else, and not have to worry about what happens to my status_update.txt file next week when I run the tool again.

On the other hand, some people may have regular info in there (like when they're on holiday and stuff) that they want to carry over from week to week.

Anyway, I'm too tired to think about this carefully right now.

I'll ping you tomorrow.  Nice work!

**Comment by jbech-linaro** [comment]
So, I think I've managed to implement what you were asking for, you can try this tomorrow and see whether this was what you were asking for or not:
```bash
$ jipdate.py -c -e
```

or if you want to exclude all your stories.
```bash
$ jipdate.py -c -x -e
```

With the `-e` parameter (together with `-c`), it will first grab the open issues from Jira, then it will open your EDITOR with that information. I.e., it won't touch the `status_update.txt` file at all.

Time for me to go to bed now also :)
